mysql:
  host: 'rm-bp15baic8hwo7van1io.mysql.rds.aliyuncs.com'
  port: 3306
  user: 'taowei'
  password: 'Yasi2016@'
  database: 'wmms'

cache:
  host: 'r-bp1zrvzjmpj9j8entepd.redis.rds.aliyuncs.com'
  port: 6379
  password: 'r-bp1zrvzjmpj9j8ente:Yasi2016@'
  db: 1

rabbit:
  host: '121.196.216.253'
  port: 5672

server:
  port: 5000

wx:
  app_id: "wxb5d3c94274826474"
  app_secret: "aebfe5052a8fdb870048e989d98c7f74"
