mysql:
  host: 'rm-bp15baic8hwo7van1io.mysql.rds.aliyuncs.com'
  port: 3306
  user: 'taowei'
  password: 'Yasi2016@'
  database: 'wmms'

cache:
  host: '127.0.0.1'
  port: 6379
  db: 1

server:
  port: 5000

wx:
  app_id: "wxb5d3c94274826474"
  app_secret: "aebfe5052a8fdb870048e989d98c7f74"
